
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        
  - name: stg_users
    description: "User details like name, contact, email, and address"
    columns:
      - name: user_id
        tests:
          - not_null
          - unique 

  - name: stg_addresses
    description: "address details like city, state, zipcode,country"
    columns:
      - name: address_id
        tests:
          - not_null
          - unique 

  - name: stg_events
    description: "event details session, page, user, etc"
    columns:
      - name: event_id
        tests:
          - not_null
          - unique  
      - name: user_id
        tests:
          - not_null
      - name: session_id
        tests:
          - not_null

  - name: stg_orders
    description: "order details like promo code, address, user, order at, tracking details, cost, etc"
    columns:
      - name: order_id
        tests:
          - not_null
          - unique   
      - name: user_id
        tests:
          - not_null   
      - name: address_id
        tests:
          - not_null

  - name: stg_order_items
    description: "list of products in orders and their quantities."
    columns:
      - name: order_id
        tests:
          - not_null
      - name: product_id
        tests:
          - not_null 

  - name: stg_products
    description: "product details like name, price and quanity"
    columns:
      - name: product_id
        tests:
          - not_null
          - unique

  - name: stg_promos
    description: "promo details like discount, status"
    columns:
      - name: promo_id
        tests:
          - not_null
          - unique