version: 2

sources:

  - name: tutorial # name of the source 
    schema: public # this is the schema our raw data lives in
    database: dbt # this is the name of our database

    quoting:
      database: false
      schema: false
      identifier: false

    freshness:
      warn_after: {count: 24, period: hour}
      error_after: {count: 48, period: hour}

    tables:
      - name: users 
        loaded_at_field: created_at
        description: >
          Contains demographic information about each user

      - name: addresses 
        description: >
          contains address details of users

      - name: events 
        loaded_at_field: created_at
        description: >
          contains user activity details

      - name: orders 
        loaded_at_field: created_at
        description: >
          contains order details
      
      - name: order_items 
        description: >
          items details of orders

      - name: products 
        description: >
          product details

      - name: promos 
        description: >
          product details
      
